name: Static Site CI
on:
 push:
   branches:
     - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Simulate a build step
       run: echo "Build step for static website completed!"
     - name: Success message
       run: echo "Code is ready for deployment to AWS"
